baseURL = "http://sebastianjuhl.com/"
languageCode = "en-us"
title = "Sebastian Juhl"
theme = "hyde-hyde"
googleAnalytics = "UA-116127093-1"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
  	disable = false
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

  # Enable global LaTeX math rendering?
  # If false, you can enable it locally on a per page basis.
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Data Scientist"
  #phd = "PhD Candidate"
  job = "Data Scientist"
  author = "Sebastian Juhl"
  ateformat = "Jan 1, 2006"
  authorimage ="/profile2.png"
  
[params.social]
    email = "sebastian.juhl@t-online.de"
	linkedin = "/sjuhl"
    github = "sjuhl"
	googlescholar = "Sebastian Juhl"
    #stackoverflow = "<username>"
	
[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
  
#[[menu.main]]
    #name = "About"
    #identifier = "about"
    #weight = 2
    #url = "/about/"
	
[[menu.main]]
    name = "Research"
    identifier = "research"
    weight = 3
    url = "/research/"
	
[[menu.main]]
    name = "Software"
    identifier = "software"
    weight = 4
    url = "/software/"
	
[[menu.main]]
    name = "Presentations"
    identifier = "presentations"
    weight = 5
    url = "/presentations/"

#[[menu.main]]
    #name = "CV"
    #identifier = "cv"
    #weight = 6
    #url = "/cv/"

