---
layout: archive
title: ""
permalink: /publications/spacebetween
author_profile: true
---

## The Space Between: How Ideological Similarity Limits the Effectiveness of Ambiguity

*(with Victor Shin)*

**Journal of Elections, Public Opinion and Parties**, forthcoming

> Recent research has shown that political actors strategically conceal their ideological position and gain electoral benefits by presenting themselves as if they were closer to the voter. Ideological ambiguity may seem like a rewarding strategy, but there are clear limits. In this project, we explore the limits of ambiguity and argue that voters make a value judgment on the party’s signal based on its ideological distinctiveness. Our theory is based on the desire of parties to offer ideological positions that are clearly distinguishable from neighboring parties. With the use of Comparative Study of Election Systems (CSES) data, we provide clear evidence that voters’ perceived distance to parties and their willingness to vote for the party are conditioned by both ambiguity and ideological distinctiveness. Indeed, too much ideological overlap in the voters’ perceptions of parties’ positions dampens the potential rewards from strategic ambiguity. We also provide the first evidence that voters reject parties whose ideologies cannot be distinguished from those of rival parties. Our research offers answers to recent dilemmas related to responsible party government, party messaging, and the diffusion of campaign strategies. 

  [[Article]](..//files/SB-AM.pdf){:target="_blank"} [[Reproduction]](https://doi.org/10.7910/DVN/BMBRYS){:target="_blank"} [[Appendix]](..//files/SB-A.pdf)
